name: Shell CVE Scan

permissions:
  security-events: write
  contents: read

on:
  push:
    branches: [main, stage, dev]
  pull_request:
    branches: [main, stage, dev]

jobs:
  shellcheck_scan:
    name: ShellCheck Scan
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        shell: [bash, sh, dash, ksh]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Run ShellCheck with SARIF output
        uses: reactive-firewall/shellcheck-scan@v1.2
        with:
          shell-format: ${{ matrix.shell }}
          publish-artifacts: no